### ISSUE TITLE
DevNexus Conference

### ISSUE THREAD

**Issue by rhagarty** [OpenLiberty/blogs#2132] opened 2022-03-29 15:32 UTC
Blog post about what we will be presenting at DevNexus in Atlanta during week of April 11-15, 2022

**Comment by yeekangc** [comment] 2022-03-29 19:16
@GraceJansen @dmuelle

**Comment by yeekangc** [comment] 2022-03-29 19:16
Rich is putting a draft together.

**Comment by yeekangc** [comment] 2022-03-29 19:23
This is a duplicate of #2118.  We can close the other issue.

**Comment by rhagarty** [comment] 2022-03-29 19:24
interesting... I can be assigned, but I can't push

**Comment by rhagarty** [comment] 2022-03-29 20:11
working now. Pls review draft - https://github.com/OpenLiberty/blogs/pull/2133

**Comment by yeekangc** [comment] 2022-04-01 15:39
@rhagarty, we should update the metadata your profile and your photo.

**Comment by yeekangc** [comment] 2022-04-01 15:41
I will add/update in the PR I am working on.

**Comment by rhagarty** [comment] 2022-04-01 15:49
> @rhagarty, we should update the metadata your profile and your photo.

I am listed as a co-author, and it points to my github repo and photo (old, but works). This matches what Grace has. Is that sufficient, or is there other bio stuff that needs updating?

**Comment by yeekangc** [comment] 2022-04-01 15:50
I realized that after the fact.  You can be the author directly.  =)

**Comment by rhagarty** [comment] 2022-04-01 15:51
I stole most of this from an old blog from Grace, so she deserves the author tag

**Comment by yeekangc** [comment] 2022-04-07 18:41
Missed your comment above but thank you, Rich.

This has been published.  Closing.

**Closed as completed by yeekangc** 2022-04-07 18:41 UTC
